name: Building Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  QWT_INCLUDE_DIR: ${{ github.workspace }}\source_code\Vendors\Qwt\src
  QWT_LIBRARY_RELEASE: ${{ github.workspace }}\source_code\Vendors\Qwt\x64\Release\qwt.lib
  QWT_LIBRARY_DEBUG: ${{ github.workspace }}\source_code\Vendors\Qwt\x64\Debug\qwtd.lib
  DLL_DIR: ${{ github.workspace }}\source_code\Vendors\RequiredDLLs\

jobs:
  buildUsingCMake:
    name: buildUsingCMakeJob
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.12.11'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DQT_DIR=${{env.QT_DIR}} -DQWT_INCLUDE_DIR=${{env.QWT_INCLUDE_DIR}} -DQWT_LIBRARY_RELEASE=${{env.QWT_LIBRARY_RELEASE}} -DQWT_LIBRARY_DEBUG=${{env.QWT_LIBRARY_DEBUG}} -DDLL_DIR=${{env.DLL_DIR}}

      
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload Exe File
      uses: actions/upload-artifact@v3
      with:
        name: exeArtifact
        path: "build/Release/"
    
    #- name: Install AutoIt
    #  run: choco install autoit -y
    # 
    #- name: Run AutoIt Script
    #  run: C:\\Progra~2\\AutoIt3\\AutoIt3.exe .github\workflows\run_and_screenshot.au3
    #  
    #- name: Upload screenshot as artifact
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: screenshot
    #    path: "screenshot.png"
      
  ReleaseArtifact:
    name: Release Project
    runs-on: windows-latest
    needs: buildUsingCMake
    steps:
    - name: Download exe
      uses: actions/download-artifact@v3
      with:
        name: exeArtifact
        
    - name: Output Current Files
      run: ls -R

    - name: Create Zip
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'ProMaIDeS.zip'

    - name: Add binaries to Release Tag
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: GitHubActions
        file: ./ProMaIDes.zip
        asset_name: ProMaIDeS-Win10-x64-alpha-v${{github.run_number}}.zip
        overwrite: true
        prerelease: false
        body: "Generated Automatically by Github Actions" 